const GET_CARS = 'GET_CARS';
const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
const GET_CARS_FAILURE = 'GET_CARS_FAILURE';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
const SHOW_SELECTED_CAR = 'SHOW_SELECTED_CAR';
const DELETE_CAR = 'DELETE_CAR';
const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
const DELETE_CAR_FAILURE = 'DELETE_CAR_FAILURE';
const POST_CAR = 'POST_CAR';
const POST_CAR_SUCCESS = 'POST_CAR_SUCCESS';
const POST_CAR_FAILURE = 'POST_CAR_FAILURE';

export {
  GET_CARS,
  GET_CARS_SUCCESS,
  GET_CARS_FAILURE,
  SET_SEARCH_BAR,
  SHOW_SELECTED_CAR,
  DELETE_CAR,
  DELETE_CAR_SUCCESS,
  DELETE_CAR_FAILURE,
  POST_CAR,
  POST_CAR_SUCCESS,
  POST_CAR_FAILURE,
};
